Exclude:
  - '*.sif'
  - figures
  - saved_model
  - README.md
Resources:
  Nodes: 1
  Queue: devel
Environment:
  Variables:
    GIT_PYTHON_REFRESH: quiet
  PreRunCommandOnComputeNode: >-
    module load Stages/2022  GCCcore/.11.2.0 Python/3.9.6 CUDA/11.5
    numactl/2.0.14 cuDNN/8.3.1.22-CUDA-11.5 ecCodes/2.22.1 parallel/20210722
    GCC/11.2.0 OpenMPI/4.1.1 CDO/2.0.2; source
    /p/scratch/deepacf/maelstrom/grau1/ap4/bin/activate
UnicoreApiUrl: https://zam2125.zam.kfa-juelich.de:9112/JUWELS/rest/core
